name: Build & CI/CD VPS

concurrency:
  group: deploy-vps-prod
  cancel-in-progress: false

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Build & CI/CD VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        # env:
          # VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY }}
          # VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN }}
          # VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}
          # VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET }}
          # VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          # VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID }}
          # VITE_LOTS_INSTALLER: ${{ secrets.VITE_LOTS_INSTALLER }}
        run: npm run build
          
      - name: Clean old project folder on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf ~/ppdbmtsn1wk-react

      - name: Copy dist & docker files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist,Dockerfile,docker-compose.yml"
          target: "~/ppdbmtsn1wk-react"
        
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/ppdbmtsn1wk-react
            sudo docker compose down
            sudo docker compose build
            sudo docker compose up -d
            sudo docker image prune -f

      # - name: Send Telegram notification (Success)
      #   if: success()
      #   env:
      #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      #   run: |
      #     COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
      #     AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
      #     COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          
      #     curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
      #       -d chat_id="$TELEGRAM_CHAT_ID" \
      #       -d text="✅ CI/CD Sukses!%0AProject *ppdbmtsn1wk-react* berhasil dideploy ke VPS 🎉%0A%0A📝 *Commit:* \`$COMMIT_MESSAGE\`%0A👤 *Author:* $AUTHOR_NAME%0A🔗 [Lihat Commit]($COMMIT_URL)" \
      #       -d parse_mode=Markdown

      # - name: Send Discord notification (Success)
      #   if: success()
      #   env:
      #     DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #   run: |
      #     COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
      #     AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
      #     COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          
      #     curl -s -X POST "$DISCORD_WEBHOOK_URL" \
      #       -H "Content-Type: application/json" \
      #       -d "{\"username\":\"LOTS-CI/CD\",\"avatar_url\":\"https://github.com/identicons/$AUTHOR_NAME.png\",\"embeds\":[{\"title\":\"✅ CI/CD Success\",\"description\":\"Project **ppdbmtsn1wk-react** successfully deployed to VPS 🎉\",\"color\":65280,\"fields\":[{\"name\":\"Commit\",\"value\":\"\`$COMMIT_MESSAGE\`\",\"inline\":true},{\"name\":\"Author\",\"value\":\"$AUTHOR_NAME\",\"inline\":true},{\"name\":\"View Commit\",\"value\":\"[Click here]($COMMIT_URL)\",\"inline\":true}]}]}"

      # - name: Send failure Telegram notification
      #   if: failure()
      #   env:
      #     TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      #     TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      #   run: |
      #     COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
      #     AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
      #     COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          
      #     curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
      #       -d chat_id="$TELEGRAM_CHAT_ID" \
      #       -d text="❌ CI/CD Gagal!%0AProject *ppdbmtsn1wk-react* gagal dideploy ke VPS ⚠️%0A%0A📝 *Commit:* \`$COMMIT_MESSAGE\`%0A👤 *Author:* $AUTHOR_NAME%0A🔗 [Lihat Commit]($COMMIT_URL)" \
      #       -d parse_mode=Markdown

      # - name: Send failure Discord notification
      #   if: failure()
      #   env:
      #     DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      #   run: |
      #     COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
      #     AUTHOR_NAME=$(git log -1 --pretty=format:"%an")
      #     COMMIT_URL="https://github.com/${{ github.repository }}/commit/${{ github.sha }}"
          
      #     curl -s -X POST "$DISCORD_WEBHOOK_URL" \
      #       -H "Content-Type: application/json" \
      #       -d "{\"username\":\"LOTS-CI/CD\",\"avatar_url\":\"https://github.com/identicons/$AUTHOR_NAME.png\",\"embeds\":[{\"title\":\"❌ CI/CD Failed\",\"description\":\"Project **ppdbmtsn1wk-react** failed to deploy to VPS ⚠️\",\"color\":16711680,\"fields\":[{\"name\":\"Commit\",\"value\":\"\`$COMMIT_MESSAGE\`\",\"inline\":true},{\"name\":\"Author\",\"value\":\"$AUTHOR_NAME\",\"inline\":true},{\"name\":\"View Commit\",\"value\":\"[Click here]($COMMIT_URL)\",\"inline\":true}]}]}"
