name: Build & CI/CD VPS

concurrency:
  group: deploy-vps-prod
  cancel-in-progress: false

on:
  push:
    branches:
      - prod

jobs:
  deploy:
    name: Build & CI/CD VPS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm install

      - name: Build project
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
          VITE_WILAYAH_API_URL: ${{ secrets.VITE_WILAYAH_API_URL }}
        run: npm run build
          
      - name: Clean old project folder on VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            rm -rf ~/ppdbmtsn1wk-react

      - name: Copy dist & docker files to VPS
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "dist,Dockerfile,docker-compose.yml,nginx.conf"
          target: "~/ppdbmtsn1wk-react"
        
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/ppdbmtsn1wk-react
            sudo docker compose down
            sudo docker compose build
            sudo docker compose up -d
            sudo docker image prune -f